# Params
- display: "Poems__First Poem"
  ui_component: "string"
  doc: "text of the first poem"
  default: "hello hello!"
  output:
    params: ["poem"]

- display: "Poems__Second Poem"
  ui_component: "string"
  doc: "text of the second poem"
  output:
    params: ["poem_2"]

- display: "Counting__What to count"
  ui_component: "dropdown"
  doc: "Select how to count"
  default: "chars"
  input:
    preset:
      options: ["bytes", "counts", "words"]
  output:
    params: ["count_method"]

- display: "Additional_Work__additional arithmetic to perform"
  ui_component: "dropdown"
  doc: "Select whether additional math should be applied to counted values"
  default: "Sum only"
  input:
    preset:
      options: ["Sum only", "Sum, then add a value", "Sum, then multiply"]
  output:
    params: ["arithmetic_method"]

- display: "Additional_Work__value_to_add"
  ui_component: "int"
  default: 2
  output:
    params: ["arithmetic_add"]

- display: "Additional_Work__value_to_multiply"
  ui_component: "int"
  default: 3
  output:
    params: ["arithmetic_multiply"]

# Input Steps - None

# Outputs
- display: "Count from First Poem"
  ui_component: "raw"
  input:
    files: ["count_poem.txt"]

- display: "Count from Second Poem"
  ui_component: "raw"
  input:
    files: ["count_poem_2.txt"]

- display: "Arithmetic Result"
  ui_component: "raw"
  input:
    files: [arithmetic.txt]

- display: "Summary of Everything"
  ui_component: "markdown"
  input:
    files: ["summary.md"]